apiVersion: batch/v1
kind: Job
metadata:
  name: user-service-database-initialiser-job
  namespace: peerprep
spec:
  template:
    metadata:
      namespace: peerprep
      labels:
        app: user-service-database-initialiser
    spec:
      containers:
        - name: user-service-database-initialiser
          image: ghcr.io/cs3219-ay2324s1-g04/peerprep_user_service_database_initialiser:demo
          env:
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: user-service-database-client-config-map
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-database-client-secret
                  key: database-password
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-service-database-client-config-map
                  key: database-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-service-database-client-config-map
                  key: database-port
            - name: DATABASE_SHOULD_USE_TLS
              valueFrom:
                configMapKeyRef:
                  name: user-service-database-client-config-map
                  key: database-should-use-tls
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-service-database-client-config-map
                  key: database-name
            - name: DATABASE_CONNECTION_TIMEOUT_MILLIS
              valueFrom:
                configMapKeyRef:
                  name: user-service-database-client-config-map
                  key: database-connection-timeout-millis
            - name: DATABASE_MAX_CLIENT_COUNT
              valueFrom:
                configMapKeyRef:
                  name: user-service-database-client-config-map
                  key: database-max-client-count
            - name: HASH_COST
              valueFrom:
                configMapKeyRef:
                  name: user-service-core-config-map
                  key: hash-cost
            - name: ADMIN_EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: user-service-database-initialiser-config-map
                  key: admin-email-address
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-database-initialiser-secret
                  key: admin-password
            - name: SHOULD_FORCE_INITIALISATION
              value: 'false'
      restartPolicy: OnFailure
  backoffLimit: 10
