services:
  database:
    image: peerprep_user_service_database
    build: ./database
    networks:
      network1:
        ipv4_address: 172.100.0.2
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      HASH_COST: ${HASH_COST}
  api:
    depends_on:
      - database
    image: peerprep_user_service_api
    build: ./api
    networks:
      network1:
        ipv4_address: 172.100.0.3
    ports:
      - "3000:3000"
    environment:
      PG_HOST: "172.100.0.2"
      PG_PASSWORD: ${PG_PASSWORD}
      PG_USER: ${PG_USER}
      PG_DATABASE: ${PG_DATABASE}
      PG_PORT: ${PG_PORT}
      PG_POOL_CONNECTION_TIMEOUT_MILLIS: ${PG_POOL_CONNECTION_TIMEOUT_MILLIS}
      PG_POOL_IDLE_TIMEOUT_MILLIS: ${PG_POOL_IDLE_TIMEOUT_MILLIS}
      PG_POOL_MAX: ${PG_POOL_MAX}
      PORT: ${PORT}
      HASH_COST: ${HASH_COST}
      SESSION_EXPIRE_MILLIS: ${SESSION_EXPIRE_MILLIS}

networks:
  network1:
    ipam:
      config:
        - subnet: 172.100.0.0/16
