services:
  database:
    image: peerprep_user_service_database
    build: ./database
    networks:
      network1:
        ipv4_address: 172.100.0.2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      HASH_COST: ${HASH_COST}
  api:
    depends_on:
      - database
    image: peerprep_user_service_api
    build: ./api
    networks:
      network1:
        ipv4_address: 172.100.0.3
    ports:
      - "${PORT}:${PORT}"
    environment:
      POSTGRES_HOST: "172.100.0.2"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_POOL_CONNECTION_TIMEOUT_MILLIS: ${POSTGRES_POOL_CONNECTION_TIMEOUT_MILLIS}
      POSTGRES_POOL_IDLE_TIMEOUT_MILLIS: ${POSTGRES_POOL_IDLE_TIMEOUT_MILLIS}
      POSTGRES_POOL_MAX: ${POSTGRES_POOL_MAX}
      PORT: ${PORT}
      HASH_COST: ${HASH_COST}
      SESSION_EXPIRE_MILLIS: ${SESSION_EXPIRE_MILLIS}

networks:
  network1:
    ipam:
      config:
        - subnet: 172.100.0.0/16
