services:
  user_service_database:
    image: peerprep_user_service_database
    build: ./database
    networks:
      - network1
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      ADMIN_EMAIL_ADDRESS: ${ADMIN_EMAIL_ADDRESS}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      HASH_COST: ${HASH_COST}

  user_service_api:
    image: peerprep_user_service_api
    build: ./api
    networks:
      - network1
    ports:
      - "${PORT}:3000"
    environment:
      DATABASE_HOST: "user_service_database"
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CONNECTION_TIMEOUT_MILLIS: ${DATABASE_CONNECTION_TIMEOUT_MILLIS}
      DATABASE_IDLE_TIMEOUT_MILLIS: ${DATABASE_IDLE_TIMEOUT_MILLIS}
      DATABASE_MAX_CLIENT_COUNT: ${DATABASE_MAX_CLIENT_COUNT}
      PORT: 3000
      HASH_COST: ${HASH_COST}
      SESSION_EXPIRE_MILLIS: ${SESSION_EXPIRE_MILLIS}
    depends_on:
      - user_service_database
    restart: unless-stopped

networks:
  network1:
    name: peerprep
