services:
  user_service_database:
    image: postgres:16-bookworm
    networks:
      - peerprep_network
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped

  user_service_database_initialiser:
    image: ghcr.io/cs3219-ay2324s1-g04/peerprep_user_service_database_initialiser
    build:
      context: .
      dockerfile: ./dockerfiles/database_initialiser.dockerfile
    networks:
      - peerprep_network
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: 'user_service_database'
      DATABASE_PORT: 5432
      DATABASE_SHOULD_USE_TLS: false
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CONNECTION_TIMEOUT_MILLIS: ${DATABASE_CONNECTION_TIMEOUT_MILLIS}
      DATABASE_MAX_CLIENT_COUNT: ${DATABASE_MAX_CLIENT_COUNT}
      HASH_COST: ${HASH_COST}
      ADMIN_EMAIL_ADDRESS: ${ADMIN_EMAIL_ADDRESS}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SHOULD_FORCE_INITIALISATION: ${SHOULD_FORCE_INITIALISATION}
    depends_on:
      - user_service_database
    restart: on-failure

  user_service_api:
    image: ghcr.io/cs3219-ay2324s1-g04/peerprep_user_service_api
    build:
      context: .
      dockerfile: ./dockerfiles/api.dockerfile
    networks:
      - peerprep_network
    ports:
      - '${API_EXPOSED_PORT}:9000'
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: 'user_service_database'
      DATABASE_PORT: 5432
      DATABASE_SHOULD_USE_TLS: false
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CONNECTION_TIMEOUT_MILLIS: ${DATABASE_CONNECTION_TIMEOUT_MILLIS}
      DATABASE_MAX_CLIENT_COUNT: ${DATABASE_MAX_CLIENT_COUNT}
      HASH_COST: ${HASH_COST}
      ACCESS_TOKEN_PRIVATE_KEY: ${ACCESS_TOKEN_PRIVATE_KEY}
      ACCESS_TOKEN_PUBLIC_KEY: ${ACCESS_TOKEN_PUBLIC_KEY}
      SESSION_EXPIRE_MILLIS: ${SESSION_EXPIRE_MILLIS}
      ACCESS_TOKEN_EXPIRE_MILLIS: ${ACCESS_TOKEN_EXPIRE_MILLIS}
      PORT: 9000
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - user_service_database
    restart: unless-stopped

networks:
  peerprep_network:
    name: peerprep
    external: true
