apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  creationTimestamp: null
  name: user-service-database-initialiser-secret
  namespace: peerprep
spec:
  encryptedData:
    admin-password: AgCviwo6ZXonSDeUay9tmRh4iF+EoJZKD3NxuIs1dPnEu5oI0yvt44lJZjqhURQosPtBk8j7SoitklEAHiUULwOhODDeLvKZnlpCKFlVOtd+lKUwke9l8Y68DiH9egQiQdopOxikixSjTE7ZnFe4usLLEhtaJgxkzBz6NRdmDf7eiWOH3rNIJDZJMLgPEaGtbGJwun4wA5zhrQYOflo4234C3jm2PdUIHKiSDVdF+E08XAMuz9PE3EmVceII36Ur2aaKq7HCn8tWTYdZ7e7i0eKxfspypuN7uawDWd7jHenmJTyIiGJStRHXwozUyrXb5fcbzi99Wf4znfaP8MhrLvg4llxgySCgtMQDPvCQ1kUQBEM4zUZusqq0uqQb1NPAw1yV0GQAyZYJ/dIaJKAZGQSDt/+JaR4H/aH/FC5i5hjpkBg8uwD2iVk/dympr/qmOyXUi+DAmY+FYhLDpZNIplKKssBguvoytxGuNNv5EK8FKyXWZzo+BpIbWkrYXocRRK+SqNumXASWv9xLrnPpqvCpCdR31Ls2sG7js/IDRqnH29pAf7M53gfmXEkPMoChEc4BFahjoQFoUebAnHawxi/fPRl0+qJojzunjAnFlEZRx55BoStBQnPe1ZAYLQiZon7jtj6jxxYysjiZC1oGYmNEkzwBNaS9rz3z99W4rNiD6TCRurwRbLDlr6udOEnuK1//u8L2V6LXpe6IM7abbA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      creationTimestamp: null
      name: user-service-database-initialiser-secret
      namespace: peerprep
    type: Opaque
