apiVersion: v1
kind: Secret
metadata:
  name: user-service-database-client-secret
  namespace: peerprep
type: Opaque
data:
  database-user: # TODO Set this (encode in base64)
  database-password: # TODO: Set this (encode in base64)
  database-host: # TODO: Set this (encode in base64)
  database-port: # TODO: Set this (encode in base64)
  database-name: # TODO: Set this (encode in base64)
