apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-database-client-config-map
  namespace: peerprep
data:
  database-user: fgnrvorv
  database-host: satao.db.elephantsql.com
  database-port: '5432'
  database-should-use-tls: 'true'
  database-name: fgnrvorv
  database-connection-timeout-millis: '0'

  # This value should be much higher for actual deployment (e.g. 10 or 20). The
  # reason why it is set so low is due to free tier database concurrent
  # connection restrictions.
  database-max-client-count: '1'
