apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-database-client-config-map
  namespace: peerprep # Defaults to "default"
data:
  database-connection-timeout-millis: '0'
  database-idle-timeout-millis: '10000'
  database-max-client-count: '20'
