CREATE TYPE USER_ROLES AS ENUM ('admin', 'maintainer', 'user');

CREATE TABLE User_Profiles (
  user_id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role USER_ROLES NOT NULL DEFAULT 'user'
);

CREATE TABLE User_Credentials (
  user_id INTEGER PRIMARY KEY REFERENCES User_Profiles ON DELETE CASCADE ON UPDATE CASCADE,
  password_hash VARCHAR(60) NOT NULL
);

CREATE TABLE User_Sessions (
  token CHAR(36) PRIMARY KEY,
  user_id INTEGER REFERENCES User_Profiles ON DELETE CASCADE ON UPDATE CASCADE,
  login_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expire_time TIMESTAMP NOT NULL CHECK (expire_time > CURRENT_TIMESTAMP)
);
